## Developer scripts/UI Module

##################################################
## Customize
##################################################

homeassistant:
  customize:    
    script.reload:
      icon: mdi:reload
      #show_last_changed: true
    script.ir_learn:
      icon: mdi:remote
      #show_last_changed: true

##################################################
## Groups
##################################################

group:
  developer:
    name: Developer
    entities:
      - script.reload
      - script.ir_learn
      - input_select.activity
      - input_select.ha_mode
      - script.restart_ha

##################################################
## Scripts
##################################################

script:
  reload:
    alias: Reload
    sequence:            
      - service: python_script.summary
      #- service: python_script.reload
      #- service: homeassistant.reload_core_config
      #- service: frontend.reload_themes
