homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: metric
  time_zone: !secret time_zone
  customize: !include config/customize.yaml

frontend:
  extra_html_url:
    - /local/custom_ui/state-card-floorplan.html
    - /local/custom_ui/state-card-tiles.html
  extra_html_url_es5:
    - /local/custom_ui/state-card-tiles_es5.html

config:

updater:

# Mosquitto MQTT Broker
mqtt:
  broker: 127.0.0.1
  port: 1883
  protocol: 3.1
  username: !secret mqtt_username
  password: !secret mqtt_password

conversation:

history:

logbook:

map:

sun:

tts:
  - platform: google

cloud:

switch:
  - platform: deluge
    host: 192.168.0.104
    port: 8080
    username: !secret torrent_username
    password: !secret torrent_password

notify:
  - platform: kodi
    name: Kodi-notify
    host: 192.168.0.104
    port: 8080
    username: !secret mp_username
    password: !secret mp_password

# Media Player
media_player:
  - platform: kodi
    name: Kodi
    host: 192.168.0.104
    port: 8080
    username: !secret mp_username
    password: !secret mp_password

binary_sensor:
  - platform: mqtt
    state_topic: dummy/floorplan/sensor
    name: Floorplan

input_boolean:
  dummy_tiles:
  switch1:

panel_custom:
  - name: floorplan
    sidebar_title: Floorplan
    sidebar_icon: mdi:home
    url_path: floorplan
    config: !include config/floorplan.yaml

panel_iframe: !include config/panel.yaml
sensor: !include config/sensors.yaml
light: !include config/lights.yaml
group: !include config/groups.yaml
automation: !include config/automations.yaml
script: !include config/scripts.yaml
