binary_sensor.floorplan: 
  custom_ui_state_card: state-card-floorplan
  config: !include floorplan.yaml

light.kitchen:
  custom_ui_state_card: state-card-tiles
  config:
    entities:
      - entity: light.kitchen 
